language: node_js
env:
  - DB_TEST_DATABASE_URL=postgres://postgres:@localhost:5432/travis SECRET_KEY=TEST
node_js:
  - "stable"
before_install:
  - npm install -g npm@latest
cache:
  directories:
    - "node_modules"

before_script:
  - psql -U postgres -d postgres -a -f ./server/db/travisIndexTest.sql
after_success:
  -  npm run coverage
services:
  - postgresql
