language: node_js
env:
  - DB_TEST_DATABASE_URL=postgres://damola:damola@localhost:5432/travis
  - SECRET_KEY='TEST'
node_js:
  - "stable"
before_install:
  - npm install -g npm@latest
cache:
  directories:
    - "node_modules"

before_script:
  - psql -c "CREATE DATABASE travis;" -U postgres
  - psql -c "CREATE USER damola WITH PASSWORD 'damola';" -U postgres
after_success:
  -  npm run coverage
services:
  - postgresql
