CREATE DATABASE travis;
\c travis
CREATE TABLE IF NOT EXISTS USERS(
ID SERIAL PRIMARY KEY,
FIRST_NAME VARCHAR(25) NOT NULL,
LAST_NAME VARCHAR(25) NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
PASSWORD VARCHAR(90) NOT NULL,
JOB_TITLE VARCHAR(30) NOT NULL,
DEPARTMENT VARCHAR(30) NOT NULL,
PROFILE SMALLINT NOT NULL,
LOCATION VARCHAR(160) NOT NULL,
UPGRADE_ID UUID NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS REQUESTS(
ID UUID PRIMARY KEY NOT NULL,
TITLE VARCHAR(50) NOT NULL,
DESCRIPTION VARCHAR(288) NOT NULL,
status SMALLINT NOT NULL,
type SMALLINT NOT NULL,
date_submitted date NOT NULL,
last_edited date NOT NULL,
date_resolved date,
LOCATION VARCHAR(160) NOT NULL,
REASON VARCHAR(288),
userid INT references users(ID));
\dt
\du
