const requestsColumns = `
title,
description,
status,
type,
date_submitted,
last_edited,
location,
userid
`;
const requestsValues = [
  'Broken Toilet',
  'The toilet is broken please fix it',
  0,
  1,
  new Date(),
  new Date(),
  '4 Tawdry Lane',
  1,
  'Broken Lightbulb',
  'The lightbulb is broken please fix it',
  0,
  0,
  new Date(),
  new Date(),
  '7 brammal lane',
  1,
  'Broken faucet',
  'The tap is broken',
  0,
  0,
  new Date(),
  new Date(),
  '6 brammal lane',
  1,
  'Broken chair',
  'The chair is broken please fix it',
  1,
  1,
  new Date(),
  new Date(),
  '8 brammal lane',
  1
];
export { requestsColumns, requestsValues };
